### ISSUE TITLE
FlagsmithProviderProps is missing api prop.

### ISSUE THREAD

**Issue by mateuszCiezczak** [TheMagoo73/flagsmith-react#30]
The `api` prop is missing from type definition. 
https://github.com/TheMagoo73/flagsmith-react/blob/3c82d10578855a89ebfae860513e19b185de53f9/index.d.ts#L94-L107

**Comment by TheMagoo73** [comment]
Released in 9c745dd - v1.2.1. Thanks for your PR @mateuszCiezczak
